'use server';
/**
 * @fileOverview An AI agent that generates a detailed character description from free text input.
 *
 * - generateCharacterDescription - A function that generates a character description.
 * - GenerateCharacterDescriptionInput - The input type for the generateCharacterDescription function.
 * - GenerateCharacterDescriptionOutput - The return type for the generateCharacterDescription function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GenerateCharacterDescriptionInputSchema = z.object({
  characterDescription: z
    .string()
    .describe("A free-text description of the character's appearance, personality, and backstory."),
});
export type GenerateCharacterDescriptionInput = z.infer<typeof GenerateCharacterDescriptionInputSchema>;

const GenerateCharacterDescriptionOutputSchema = z.object({
  detailedDescription: z
    .string()
    .describe('A detailed character profile generated by the AI.'),
});
export type GenerateCharacterDescriptionOutput = z.infer<typeof GenerateCharacterDescriptionOutputSchema>;

export async function generateCharacterDescription(
  input: GenerateCharacterDescriptionInput
): Promise<GenerateCharacterDescriptionOutput> {
  return generateCharacterDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCharacterDescriptionPrompt',
  input: {
    schema: z.object({
      characterDescription: z
        .string()
        .describe("A free-text description of the character's appearance, personality, and backstory."),
    }),
  },
  output: {
    schema: z.object({
      detailedDescription: z
        .string()
        .describe('A detailed character profile generated by the AI.'),
    }),
  },
  prompt: `You are a fantasy story writer who is very good at coming up with characters.

  Based on the following description, write a detailed character profile.

  Description: {{{characterDescription}}}
  `,
});

const generateCharacterDescriptionFlow = ai.defineFlow<
  typeof GenerateCharacterDescriptionInputSchema,
  typeof GenerateCharacterDescriptionOutputSchema
>({
  name: 'generateCharacterDescriptionFlow',
  inputSchema: GenerateCharacterDescriptionInputSchema,
  outputSchema: GenerateCharacterDescriptionOutputSchema,
},
async input => {
  const {output} = await prompt(input);
  return output!;
});
